dist: xenial
language: python

cache: pip

branches:
  only:
    - master

python:
  - 3.6
  - 3.7
  - 3.8

stages:
  - check
  - test

matrix:
  include:
    -
      stage: check
      python: 3.7
      script: scripts/check

  fast_finish: true

script: scripts/test
