#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="httpcore tests"
SOURCE_FILES_WITHOUT_SYNC=$(find httpcore tests -maxdepth 1 -not -path "*/_sync*" -type d)

set -x

${PREFIX}ruff check --show-source $SOURCE_FILES
${PREFIX}ruff format $SOURCE_FILES_WITHOUT_SYNC --diff
${PREFIX}mypy $SOURCE_FILES
scripts/unasync --check
