#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

SOURCE_DIR="docs"
OUT_DIR="build/html"

COMMAND="$1"
shift

set -x

if [ "$COMMAND" = "build" ]; then
    ${PREFIX}sphinx-build $SOURCE_DIR $OUT_DIR
elif [ "$COMMAND" = "gh-deploy" ]; then
    scripts/docs build
    ${PREFIX}ghp-import $OUT_DIR -np -m "Deployed $(git rev-parse --short HEAD)" $@
else
    ${PREFIX}sphinx-autobuild $SOURCE_DIR $OUT_DIR --watch httpcore/
fi
